apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello

    spec:

      imagePullSecrets:
      - name: ecr-secret

      containers:

      - name: api

        image: {{image}}

        ports:
        - containerPort: 3000
        
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DATABASE_URL
