apiVersion: v1
kind: Service

metadata:
  name: crud-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  type: LoadBalancer
  selector:
    app: crud-app

  ports:

  - port: 80
    targetPort: 3000
