name: Build and Push Backend Image

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build-container-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./backend/pnpm-lock.yaml

      - name: Install dependencies, Generate Prisma & Build TS
        working-directory: ./backend
        run: |
          pnpm install --frozen-lockfile
          pnpm prisma generate
          pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fetch ECR Outputs from CloudFormation
        run: |
          ECR_OUT=$(aws cloudformation describe-stacks --stack-name ECRStack --query "Stacks[0].Outputs" --output json)

          REPO_URI=$(echo "$ECR_OUT" | jq -r '.[] | select(.OutputKey | contains("RepositoryUri")) | .OutputValue')
          REPO_NAME=$(echo "$ECR_OUT" | jq -r '.[] | select(.OutputKey | contains("ECRRepositoryName")) | .OutputValue')

          echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ secrets.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        working-directory: ./backend
        run: |
          docker build -t ${{ env.REPO_URI }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Image to ECR
        run: |
          docker push ${{ env.REPO_URI }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
